const store = {
  users: [
    {
      id: 'admin-1',
      name: 'Admin Manager',
      email: 'admin@wanderlust.com',
      password: '$2a$10$e/0dO4v4z3e3b3w3v3u3e3u3e3u3e3u3e3u3e3u3e3u3e3u3e3u3e',
      role: 'admin',
      phone: '+1 800-555-0199',
      loyaltyPoints: 1200,
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80'
    },
    {
      id: 'user-1',
      name: 'Sophia Vance',
      email: 'user@wanderlust.com',
      password: '$2a$10$e/0dO4v4z3e3b3w3v3u3e3u3e3u3e3u3e3u3e3u3e3u3e3u3e',
      role: 'user',
      phone: '+1 555-0147',
      loyaltyPoints: 350,
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=150&q=80'
    }
  ],
  flights: [
    {
      id: 'fl-101',
      airline: 'SkyWays Express',
      flightNumber: 'SK-402',
      departureCity: 'Mumbai',
      arrivalCity: 'Goa',
      departureTime: '08:30 AM',
      arrivalTime: '09:45 AM',
      price: 3500,
      seatsAvailable: 42,
      duration: '1h 15m',
      rating: 4.8,
      logo: '✈️'
    },
    {
      id: 'fl-102',
      airline: 'Air France',
      flightNumber: 'AF-882',
      departureCity: 'Delhi',
      arrivalCity: 'Paris',
      departureTime: '01:15 PM',
      arrivalTime: '06:50 PM',
      price: 48000,
      seatsAvailable: 15,
      duration: '9h 05m',
      rating: 4.9,
      logo: '🇫🇷'
    },
    {
      id: 'fl-103',
      airline: 'Japan Airlines',
      flightNumber: 'JL-771',
      departureCity: 'Bangalore',
      arrivalCity: 'Tokyo',
      departureTime: '10:00 PM',
      arrivalTime: '07:30 AM',
      price: 52000,
      seatsAvailable: 28,
      duration: '7h 00m',
      rating: 4.9,
      logo: '🇯🇵'
    },
    {
      id: 'fl-104',
      airline: 'Emirates Air',
      flightNumber: 'EK-508',
      departureCity: 'Mumbai',
      arrivalCity: 'Dubai',
      departureTime: '04:15 PM',
      arrivalTime: '06:30 PM',
      price: 24000,
      seatsAvailable: 34,
      duration: '3h 45m',
      rating: 4.9,
      logo: '🇦🇪'
    },
    {
      id: 'fl-105',
      airline: 'Swiss Air',
      flightNumber: 'LX-302',
      departureCity: 'Delhi',
      arrivalCity: 'Zurich',
      departureTime: '02:00 AM',
      arrivalTime: '07:15 AM',
      price: 56000,
      seatsAvailable: 18,
      duration: '8h 45m',
      rating: 4.7,
      logo: '🇨🇭'
    },
    {
      id: 'fl-106',
      airline: 'Singapore Airlines',
      flightNumber: 'SQ-423',
      departureCity: 'Chennai',
      arrivalCity: 'Bali',
      departureTime: '11:20 AM',
      arrivalTime: '05:40 PM',
      price: 29000,
      seatsAvailable: 50,
      duration: '5h 50m',
      rating: 4.8,
      logo: '🇮🇩'
    },
    {
      id: 'fl-107',
      airline: 'British Airways',
      flightNumber: 'BA-117',
      departureCity: 'Delhi',
      arrivalCity: 'London',
      departureTime: '06:00 AM',
      arrivalTime: '11:30 AM',
      price: 54000,
      seatsAvailable: 22,
      duration: '10h 00m',
      rating: 4.8,
      logo: '🇬🇧'
    },
    {
      id: 'fl-108',
      airline: 'Qantas Airways',
      flightNumber: 'QF-082',
      departureCity: 'Singapore',
      arrivalCity: 'Sydney',
      departureTime: '08:15 PM',
      arrivalTime: '06:00 AM',
      price: 62000,
      seatsAvailable: 19,
      duration: '7h 45m',
      rating: 4.9,
      logo: '🇦🇺'
    },
    {
      id: 'fl-109',
      airline: 'Delta Air Lines',
      flightNumber: 'DL-405',
      departureCity: 'London',
      arrivalCity: 'New York',
      departureTime: '12:45 PM',
      arrivalTime: '04:15 PM',
      price: 58000,
      seatsAvailable: 31,
      duration: '8h 30m',
      rating: 4.7,
      logo: '🇺🇸'
    },
    {
      id: 'fl-110',
      airline: 'Qatar Airways',
      flightNumber: 'QR-571',
      departureCity: 'Mumbai',
      arrivalCity: 'Rome',
      departureTime: '03:30 AM',
      arrivalTime: '09:00 AM',
      price: 49000,
      seatsAvailable: 25,
      duration: '8h 00m',
      rating: 4.9,
      logo: '🇮🇹'
    },
    {
      id: 'fl-111',
      airline: 'Thai Airways',
      flightNumber: 'TG-316',
      departureCity: 'Kolkata',
      arrivalCity: 'Bangkok',
      departureTime: '01:50 AM',
      arrivalTime: '05:45 AM',
      price: 18500,
      seatsAvailable: 45,
      duration: '2h 25m',
      rating: 4.7,
      logo: '🇹🇭'
    },
    {
      id: 'fl-112',
      airline: 'EgyptAir',
      flightNumber: 'MS-962',
      departureCity: 'Dubai',
      arrivalCity: 'Cairo',
      departureTime: '09:30 AM',
      arrivalTime: '11:45 AM',
      price: 22000,
      seatsAvailable: 30,
      duration: '3h 15m',
      rating: 4.6,
      logo: '🇪🇬'
    },
    {
      id: 'fl-113',
      airline: 'Lufthansa',
      flightNumber: 'LH-760',
      departureCity: 'Frankfurt',
      arrivalCity: 'Barcelona',
      departureTime: '10:00 AM',
      arrivalTime: '12:05 PM',
      price: 24000,
      seatsAvailable: 38,
      duration: '2h 05m',
      rating: 4.8,
      logo: '🇪🇸'
    }
  ],
  hotels: [
    {
      id: 'ht-201',
      name: 'Grand Hyatt Beach Resort',
      city: 'Goa',
      address: 'Bambolim Beach, North Goa',
      rating: 4.8,
      pricePerNight: 8500,
      image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80',
      amenities: ['Pool', 'Free WiFi', 'Beach Front', 'Spa & Wellness', 'Bar'],
      description: 'Luxurious resort set amidst 28 acres of lush tropical gardens overlooking Bambolim Bay.',
      latitude: 15.4589,
      longitude: 73.8560,
      reviewsCount: 340
    },
    {
      id: 'ht-202',
      name: 'The Ritz Paris Riviera',
      city: 'Paris',
      address: '15 Place Vendôme, 75001 Paris, France',
      rating: 4.9,
      pricePerNight: 34000,
      image: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=800&q=80',
      amenities: ['Michelin Dining', 'Luxury Spa', 'Concierge', 'Private Balcony', 'Airport Shuttle'],
      description: 'Iconic palace hotel in the heart of Paris offering unmatched French elegance.',
      latitude: 48.8675,
      longitude: 2.3294,
      reviewsCount: 520
    },
    {
      id: 'ht-203',
      name: 'Tokyo Skyline Palace',
      city: 'Tokyo',
      address: 'Shinjuku City, Tokyo, Japan',
      rating: 4.9,
      pricePerNight: 28000,
      image: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=800&q=80',
      amenities: ['Skyline Bar', 'Onsen Spa', 'High-Speed WiFi', 'Fitness Center', 'Robot Butler'],
      description: 'Modern skyscraper hotel with breathtaking panoramic views of Mount Fuji and Tokyo skyline.',
      latitude: 35.6895,
      longitude: 139.6917,
      reviewsCount: 410
    },
    {
      id: 'ht-204',
      name: 'Burj Al Arab Luxury Resort',
      city: 'Dubai',
      address: 'Jumeirah Beach Road, Dubai, UAE',
      rating: 5.0,
      pricePerNight: 65000,
      image: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=800&q=80',
      amenities: ['Private Helicopter Pad', 'Infiniti Pool', 'Underwater Restaurant', 'Personal Butler'],
      description: 'World-renowned 7-star sail-shaped luxury monument on its own island.',
      latitude: 25.1412,
      longitude: 55.1853,
      reviewsCount: 890
    },
    {
      id: 'ht-205',
      name: 'The Ritz London Mayfair',
      city: 'London',
      address: '150 Piccadilly, London, UK',
      rating: 4.9,
      pricePerNight: 38000,
      image: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=800&q=80',
      amenities: ['High Tea Lounge', 'Chauffeur Service', 'Michelin Restaurant'],
      description: 'World-famous luxury hotel overlooking Green Park near Buckingham Palace.',
      latitude: 51.5074,
      longitude: -0.1278,
      reviewsCount: 680
    },
    {
      id: 'ht-206',
      name: 'Sydney Harbour Suite Resort',
      city: 'Sydney',
      address: 'Circular Quay West, Sydney, Australia',
      rating: 4.9,
      pricePerNight: 31000,
      image: 'https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?auto=format&fit=crop&w=800&q=80',
      amenities: ['Opera House View', 'Rooftop Bar', 'Private Yacht Dock'],
      description: 'Stunning waterfront hotel with direct views of Sydney Harbour Bridge.',
      latitude: -33.8688,
      longitude: 151.2093,
      reviewsCount: 430
    },
    {
      id: 'ht-207',
      name: 'The Plaza Fifth Avenue',
      city: 'New York',
      address: '768 5th Ave, New York, NY 10019, USA',
      rating: 4.8,
      pricePerNight: 42000,
      image: 'https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?auto=format&fit=crop&w=800&q=80',
      amenities: ['Central Park View', 'Champagne Bar', 'Guerlain Spa'],
      description: 'Timeless Manhattan landmark hotel situated at Central Park South.',
      latitude: 40.7128,
      longitude: -74.0060,
      reviewsCount: 750
    },
    {
      id: 'ht-208',
      name: 'Hotel Colosseum Grand Palace',
      city: 'Rome',
      address: 'Via Cavour 18, 00184 Rome, Italy',
      rating: 4.8,
      pricePerNight: 26000,
      image: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?auto=format&fit=crop&w=800&q=80',
      amenities: ['Rooftop Terrace', 'Italian Wine Cellar', 'Colosseum Views'],
      description: 'Historic Roman boutique hotel steps away from the Ancient Forum.',
      latitude: 41.9028,
      longitude: 12.4964,
      reviewsCount: 390
    }
  ],
  packages: [
    {
      id: 'pkg-301',
      title: 'Goa Tropical Beach & Carnival Expedition',
      destination: 'Goa',
      description: 'Experience sunny beaches, heritage Portuguese architecture, vibrant nightlife, and luxury beach resorts.',
      price: 18500,
      duration: '4 Days / 3 Nights',
      rating: 4.8,
      image: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=800&q=80',
      includedItems: ['Flight Tickets', '4-Star Resort Stay', 'Scuba & Water Sports', 'Daily Buffet Breakfast'],
      highlights: ['Baga & Calangute Beach Sunset', 'Catamaran Cruise', 'Dudhsagar Waterfalls Tour'],
      latitude: 15.2993,
      longitude: 74.1240
    },
    {
      id: 'pkg-302',
      title: 'Parisian Lights & Romance Special',
      destination: 'Paris',
      description: 'Immerse yourself in Parisian art, romantic Seine River cruises, Eiffel Tower dinner, and Louvre museum tours.',
      price: 95000,
      duration: '6 Days / 5 Nights',
      rating: 4.9,
      image: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=800&q=80',
      includedItems: ['Roundtrip Flights', '5-Star Hotel Stay', 'Eiffel Tower Priority Pass', 'Seine Dinner Cruise'],
      highlights: ['Louvre Priority Ticket', 'Versailles Palace Tour', 'Montmartre Wine Tasting'],
      latitude: 48.8566,
      longitude: 2.3522
    },
    {
      id: 'pkg-303',
      title: 'Japan Cherry Blossom & High-Speed Rail Explorer',
      destination: 'Tokyo',
      description: 'Discover futuristic Tokyo, historic Kyoto temples, Mount Fuji views, and authentic tea ceremony culture.',
      price: 125000,
      duration: '7 Days / 6 Nights',
      rating: 4.9,
      image: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=800&q=80',
      includedItems: ['International Flights', 'JR Bullet Train Pass', 'Luxury Hotel Stay', 'Guided Temple Tours'],
      highlights: ['Shibuya Crossing Tour', 'Mt Fuji 5th Station Sightseeing', 'Kyoto Bamboo Forest Walk'],
      latitude: 35.6762,
      longitude: 139.6503
    },
    {
      id: 'pkg-304',
      title: 'British Royal Heritage & Highlands Odyssey',
      destination: 'London',
      description: 'Explore London historic palaces, Big Ben, Stonehenge monoliths, and Scottish Highland lochs.',
      price: 105000,
      duration: '6 Days / 5 Nights',
      rating: 4.9,
      image: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=800&q=80',
      includedItems: ['International Flights', '4-Star Mayfair Stay', 'London Eye Priority Ticket', 'Stonehenge Day Tour'],
      highlights: ['Buckingham Palace Change of Guard', 'Windsor Castle', 'Thames Cruise'],
      latitude: 51.5074,
      longitude: -0.1278
    },
    {
      id: 'pkg-305',
      title: 'Sydney Harbour & Great Barrier Reef Discovery',
      destination: 'Sydney',
      description: 'Witness the iconic Sydney Opera House, surf at Bondi Beach, and snorkel in the world-famous Great Barrier Reef.',
      price: 135000,
      duration: '7 Days / 6 Nights',
      rating: 4.9,
      image: 'https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?auto=format&fit=crop&w=800&q=80',
      includedItems: ['Roundtrip Airfare', 'Harbour View Hotel', 'Reef Helicopter Flight', 'Snorkeling & Scuba Gear'],
      highlights: ['Sydney Opera House Backstage Tour', 'Blue Mountains Cable Car', 'Great Barrier Reef Catamaran'],
      latitude: -33.8688,
      longitude: 151.2093
    },
    {
      id: 'pkg-306',
      title: 'New York Skyline & Broadway VIP Pass',
      destination: 'New York',
      description: 'Feel the energy of Times Square, take a ferry to Statue of Liberty, view NYC from SUMMIT One Vanderbilt, and catch a Broadway show.',
      price: 115000,
      duration: '5 Days / 4 Nights',
      rating: 4.8,
      image: 'https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?auto=format&fit=crop&w=800&q=80',
      includedItems: ['Direct Flights', 'Plaza Fifth Avenue Stay', 'Broadway Show Pass', 'Statue of Liberty Ferry'],
      highlights: ['Empire State Building Sunset', 'Central Park Horse Carriage', 'Metropolitan Museum Tour'],
      latitude: 40.7128,
      longitude: -74.0060
    },
    {
      id: 'pkg-307',
      title: 'Italian Romance & Amalfi Coast Sunset Cruise',
      destination: 'Rome',
      description: 'Walk through ancient Colosseum history, toss a coin at Trevi Fountain, and sail along dramatic Amalfi Coast cliffs.',
      price: 98000,
      duration: '6 Days / 5 Nights',
      rating: 4.9,
      image: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?auto=format&fit=crop&w=800&q=80',
      includedItems: ['Flights Included', 'Rooftop Rome Hotel Stay', 'Vatican Priority Pass', 'Amalfi Catamaran Tour'],
      highlights: ['Colosseum Underground Tour', 'Positano Cliffside Lunch', 'Tuscan Vineyard Masterclass'],
      latitude: 41.9028,
      longitude: 12.4964
    },
    {
      id: 'pkg-308',
      title: 'Pyramids of Giza & Ancient Nile Wonders',
      destination: 'Cairo',
      description: 'Stand before the Great Pyramids, marvel at Sphinx monuments, and sail on a luxury Nile River cruise felucca.',
      price: 52000,
      duration: '5 Days / 4 Nights',
      rating: 4.7,
      image: 'https://images.unsplash.com/photo-1539650116574-8efeb43e2750?auto=format&fit=crop&w=800&q=80',
      includedItems: ['Flights Included', 'Nile Palace Resort Stay', 'Pyramids Camel Safari', 'Grand Egyptian Museum Pass'],
      highlights: ['Great Pyramid Interior Tour', 'Valley of the Kings Excursion', 'Old Cairo Bazaar Shopping'],
      latitude: 30.0444,
      longitude: 31.2357
    },
    {
      id: 'pkg-309',
      title: 'Thailand Tropical Paradise & Island Hopping',
      destination: 'Bangkok',
      description: 'Explore Bangkok golden temples, night food markets, and island hop through Phi Phi & Phuket crystal waters.',
      price: 38000,
      duration: '5 Days / 4 Nights',
      rating: 4.8,
      image: 'https://images.unsplash.com/photo-1508009603885-50cf7c579365?auto=format&fit=crop&w=800&q=80',
      includedItems: ['Airfare Tickets', 'Riverside Resort Stay', 'Speedboat Island Tour', 'Elephant Sanctuary Visit'],
      highlights: ['Grand Palace Guided Tour', 'James Bond Island Cruise', 'Thai Massage & Spa Session'],
      latitude: 13.7563,
      longitude: 100.5018
    }
  ],
  bookings: [
    {
      id: 'bk-501',
      userId: 'user-1',
      userName: 'Sophia Vance',
      itemType: 'package',
      itemId: 'pkg-301',
      itemTitle: 'Goa Tropical Beach & Carnival Expedition',
      destination: 'Goa',
      itemDetails: { price: 18500, duration: '4 Days / 3 Nights' },
      travelDate: '2026-08-15',
      returnDate: '2026-08-19',
      travelers: 2,
      totalPrice: 37000,
      paymentMethod: 'Stripe Credit Card',
      paymentStatus: 'paid',
      bookingStatus: 'confirmed',
      transactionId: 'TXN-99882211',
      createdAt: '2026-07-27T10:00:00.000Z'
    }
  ],
  reviews: [
    {
      id: 'rev-601',
      userId: 'user-1',
      userName: 'Sophia Vance',
      targetType: 'package',
      targetId: 'pkg-301',
      rating: 5,
      comment: 'Absolutely magical experience in Goa! Everything from hotel transfers to scuba diving was super smooth.',
      createdAt: '2026-07-27T11:30:00.000Z'
    }
  ]
};

module.exports = store;
